#!/bin/bash

mkdir -p lib3mf/lib3mf
cd lib3mf
cp ../Autogenerated/Bindings/Python/Lib3MF.py lib3mf/
sed "s/PKG_VERSION/${PKG_VERSION}/" ${RECIPE_DIR}/pyproject.toml >pyproject.toml
cp ${RECIPE_DIR}/__init__.py lib3mf

${PYTHON} -m pip install . -vv --no-deps --no-build-isolation
