{% set version = "2.2.0" %}

package:
  name: lib3mf
  version: {{ version }}

source:
  fn: lib3mf-{{ version }}.tar.gz
  url: https://github.com/3MFConsortium/lib3mf/archive/v{{ version }}.tar.gz
  sha256: 96e85e278fc5474123e3c47237dd42faaf1fdf8e182541a84af7fe84ddd3cbde
  patches:
    - windows_cmake_patch.patch  # [win]

build:
  number: 1

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - pkg-config  # [unix]
    - ninja  # [unix]
  host:
    - libzip  # [unix]
    - zlib  # [unix]

test:
  commands:
    # verify headers exist
    - test -f "${PREFIX}/include/Bindings/Cpp/lib3mf_types.hpp"                        # [unix]
    - if not exist %PREFIX%\\Library\\include\\Bindings\\Cpp\\lib3mf_types.hpp exit 1  # [win]
    # verify libraries
    - test -f "${PREFIX}/lib/lib3mf${SHLIB_EXT}"                                       # [unix]
    - if not exist %PREFIX%\\Library\\lib\\lib3mf.lib exit 1                           # [win]

about:
  home: https://github.com/3MFConsortium/lib3mf
  license: BSD-2-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - library_licenses/libzip-LICENSE-BSD-3  # [win]
    - library_licenses/zlib-LICENSE-ZLIB  # [win]
    - library_licenses/cpp-base64-LICENSE-ZLIB
  summary: A C++ implementation of the 3D Manufacturing Format file standard.

extra:
  recipe-maintainers:
    - ndevenish
    - StephenSmith25
